name: curva_longitud
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - opencv=4.7.0
  - numpy=1.23.5
  - scipy=1.10.1
  - matplotlib=3.7.1
  - scikit-image=0.20.0
  - pandas=2.0.1
  - jupyterlab=4.0.0
  - seaborn=0.12.2
  - tk=8.6.12
  - pyqt=5.15.7
  - pywavelets=1.4.1
  - nbconvert=7.3.1
  - pip=23.0.1
  - pip:
    - pillow==9.5.0
    - tqdm==4.65.0